# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    # router:
    #     resource: "%kernel.root_dir%/config/routing.yml"
    #     strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    # trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  null
        storage_factory_id: session.storage.factory.native
    assets: ~
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    # session:
    #     handler_id: null
    #     cookie_secure: auto
    #     cookie_samesite: lax

    #esi: true
    fragments: true
    php_errors:
        log: true
